AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: s3://pgpcc-harsoftng-artifacts/pdftotxt-build-artifacts/lambda_function.py
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::044433051908:role/lambda-opensearch-sr'
      Environment:
        Variables:
          TARGET_BUCKET: pgpcc-harsoftng-intermediary-store
      Layers:
        - 'arn:aws:lambda:us-east-1:044433051908:layer:pypdf-layer:1'
